### ISSUE TITLE
Standardize step size across sim speeds

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#156]
Step size (from the step button) is not consistent. It can take either four clicks or five before seeing 0.01 seconds pass on the stopwatch when in slow motion. Every click in 'Normal" motion will increase the stopwatch by a variable amount. This is all likely rounding errors.

Step size needs to be the SAME regardless of being in normal or slow motion. This is a standard. That being said, @arouinfar has requested it be the same as pendulum-lab: 0.01 seconds per step.

Seen on macOS 10.13.1 Chrome. For phetsims/QA#67.

URL: https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.28/masses-and-springs_en.html
Version: 1.0.0-dev.28 2017-11-10 19:03:33 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4918cd72","branch":"master"},"babel":{"sha":"fcbcac44","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"ca18330e","branch":"master"},"dot":{"sha":"4a1ddd12","branch":"master"},"griddle":{"sha":"6e1983be","branch":"master"},"joist":{"sha":"f34dc747","branch":"master"},"kite":{"sha":"e4c0b773","branch":"master"},"masses-and-springs":{"sha":"9d24969e","branch":"master"},"phet-core":{"sha":"ad21faf3","branch":"master"},"phetcommon":{"sha":"d957aefc","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"8e5b0892","branch":"master"},"scenery-phet":{"sha":"11c7fdb3","branch":"master"},"sherpa":{"sha":"5079b265","branch":"master"},"sun":{"sha":"71295bf0","branch":"master"},"tandem":{"sha":"547eb84d","branch":"master"},"twixt":{"sha":"13905577","branch":"master"}}

**Comment by phet-steele** [comment]
The standardization works great!

However, when I start at 0 and step 10 times, the timer displays: 00:00.10. Then when I step once more, it still says 00:00.10. Once more and it will finally say 00:00.11. Rounding errors?

**Comment by Denz1994** [comment]
Good catch @phet-steele. Could you try to replicate in master again? I think the rounding errors were fixed.

**Comment by phet-steele** [comment]
Everything is fine until 00:00.28. This is subtly different however. Pressing once will still show 00:00.28. Pressing again will skip 29 entirely and show 00:00.30. This happens in many more places if you keep going.

**Comment by Denz1994** [comment]
The rounding errors seemed to be fixed in master, could you test @phet-steele.

Also, I believe this rounding error was present in WOAS, but there isn't any play/pause functionality for the whole sim so it is difficult to reproduce. Commit 00d6a052f300219ff2e0f3f482ab1240d9e975ed may have fixed this.

**Comment by phet-steele** [comment]
Works 👍

**Comment by phet-steele** [comment]
@jonathanolson @Denz1994 I have no idea why I'm only seeing this now and didn't see this back in December (or maybe I did; you have to get lucky to see this issue).

Since we are rounding the centiseconds up and down, there are a few issues.

When centiseconds are between [99.5, 100), the timer rounds up to 100 BEFORE 100 centiseconds (1 sec) have actually elapsed, leading to:

<img width="192" alt="screen shot 2018-02-27 at 3 26 41 pm" src="https://user-images.githubusercontent.com/5863899/36758801-a9f4683a-1bd2-11e8-9f1a-c1b003d0b076.png">

There is a similar issue when centiseconds are between [100, 100.5). The timer rounds down to ".00" centiseconds. This can cause a step forward that shows no change like 

https://github.com/phetsims/masses-and-springs/issues/156#issuecomment-347337144

@jonathanolson this is all just my guess guess to explain why I'm seeing the above screenshot.

For phetsims/QA/issues/103.

**Comment by jonathanolson** [comment]
Should be fixed with the above commit. Can you verify?

**Comment by phet-steele** [comment]
This looks like a working solution in master....let's hope this issue stays dead this time.
